            - name: Docker Setup Docker
  # You may pin to the exact commit or the version.
  # uses: docker/setup-docker-action@01efb57f882e3b1a22e7cf3501dbe51287b0ecb4
  uses: docker/setup-docker-action@v4.0.0
  with:
    # Docker CE version. (e.g, v24.0.9)
    version: # optional, default is latest
    # Docker CE channel. (e.g, stable, edge or test)
    channel: # optional
    # Docker daemon JSON configuration
    daemon-config: # optional
    # Docker context name. (default setup-docker-action)
    context: # optional
    # Set DOCKER_HOST environment variable to docker socket path
    set-host: # optional, default is false
    # Enable Docker rootless mode
    rootless: # optional, default is false
          
